### ISSUE TITLE
Google Chrome App Cannot Be Downloaded/Installed 

### ISSUE THREAD

**Issue by MrBeefChief** [Narno/Battlelog-Notifier#3]
Chrome now only allows extensions that are on the Chrome Store to be used. When trying to download the extension i am greeted with " An error has occurred: Package is invalid. Details: 'Could not load extension icon 'icon-32.png'.'. " I was using this extension earlier by downloading it from your site however I can no longer do this.

**Comment by ArnaudLigny** [comment]
Hello @MrBeefChief, I think it's a problem with the build script... I will check that this week.
